### ISSUE TITLE
failed fetching

### ISSUE THREAD

**Issue by greyhwndz** [riverrun/pbkdf2_elixir#6]
I currently have the following in my `mix.exs`:
```
{:pbkdf2_elixir, "~> 1.0"}
```
but a `mix deps.get` in my terminal results in the following:
```
Request failed (:timeout)
If this happens consistently, adjust your concurrency and timeout settings:

HEX_HTTP_CONCURRENCY=1 HEX_HTTP_TIMEOUT=120 mix deps.get
** (Mix) Package fetch failed and no cached copy available (https://repo.hex.pm/tarballs/pbkdf2_elixir-1.0.2.tar)
```
I tried `HEX_HTTP_CONCURRENCY=1 HEX_HTTP_TIMEOUT=120 mix deps.get` but still it failed
is there something wrong with the repo?

**Comment by riverrun** [comment]
I will look into it, but at first glance it looks like this is a hex issue, or a problem with your connection.

**Comment by riverrun** [comment]
Any update on this issue? Is it working now?

**Comment by euler2718** [comment]
I don't know if it's related, but in my case it kept running out of memory on mix deps.get .... and when i lowered the version, it was fine.  I do think you are right that there may be an issue with hex.  I am on  windows machine.

**Comment by riverrun** [comment]
When you say you lowered the version, which version did you use?

**Comment by euler2718** [comment]
@riverrun I know it's a bit drastic, but: 0.12.4
only because I had no problems with that version.  Was following the latest programming phoenix (McCord) book.  I started the project with this version, a while back.  And when I eventually got around to the umbrella project, the 1.0 versioning caused me that issue.  I'm sure other versions would be fine, but this is all I've tried.

**Comment by riverrun** [comment]
I am not sure if it is related, but if you are using version 1 of pbkdf2, you will not need the comeonin dependency, so you can remove the comeonin line from the `deps` function in the mix.exs file.

**Comment by riverrun** [comment]
In [this issue](https://github.com/elixir-lang/elixir/issues/9374), they suggest upgrading hex to solve a similar problem. Could you try that and let me know if it works?

**Comment by kamranhossain** [comment]
Same error still happen in my environment.  All other packages are download in deps folder but this one still creating problem. Same error message here. I update hex and try other suggested things.
Only problem with this package.

![error_message](https://user-images.githubusercontent.com/19626317/74214692-a5612a00-4cc8-11ea-89a4-2afd4334e35a.png)

**Comment by kamranhossain** [comment]
@riverrun the issue is solved. After trying couple of time and updating hex. Run 
HEX_HTTP_CONCURRENCY=1 HEX_HTTP_TIMEOUT=120 mix deps.get
couple of time also.
At last it downloaded. Not sure which is main problem. Timeout was one of the main issue here but I find out comeonin hard to fetch. 
I updated my hex previously. All other deps fetch easily but this package.
Connection issue, timeout, comeonin package creates whole problem cycle.
